### ISSUE TITLE
New instructions

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/lc3-sublime#2]
I want to contribute by adding same more instructions avaliable in lc3 should I add the instructions only in `LC3-ASM.sublime-completions` or other files also need updates?

**Comment by aviaryan** [comment]
If you are adding new instructions, you will have to add them to LC3-ASM.tmLanguage too for Syntax highlighting. 
`.sublime-completions` is for autocomplete. As you can see, we have only a limited instructions in that file. We can add more instructions in that too.

**Comment by Monal5031** [comment]
Just read the `LC3-ASM.tmLanguage` seems it has all the instructions I know of but their autocomplete is not present in `.sublime-completions`

**Comment by aviaryan** [comment]
@Monal5031 Yes. I guess I didn't had the time to implement them.

**Comment by Monal5031** [comment]
@aviaryan Shall I complete them?

**Comment by aviaryan** [comment]
@Monal5031 Yes, please go ahead.

**Comment by aviaryan** [comment]
@Monal5031 Also please upload a quality .asm source code here so that we can test it. :-P

**Comment by Monal5031** [comment]
@aviaryan Will upload my lab code's folder with it. 😃

**Comment by aviaryan** [comment]
@Monal5031 Just one good file is enough. Don't add it to the repo, just upload it here as an attachment so that we can have the link.

**Comment by Monal5031** [comment]
@aviaryan But, repo already has a Test.asm

**Comment by aviaryan** [comment]
@Monal5031 Ahh, in that case just update it if needed.

**Comment by Monal5031** [comment]
@aviaryan Will update it with newly added ones.

**Comment by Monal5031** [comment]
@aviaryan  Shall I update the test.asm with a different program that will use almost nearly all the instructions?

**Comment by aviaryan** [comment]
@Monal5031 Yes you may. But let's do that as a separate PR.

**Comment by Monal5031** [comment]
@aviaryan Sorry but had already pushed the changes before I saw your comment.

**Comment by aviaryan** [comment]
More instructions in sublime-completions done in #3. Please create a new issue for a better test file.
